apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-dev
  labels:
    app: coding-with-callie
    tier: frontend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding-with-callie
      tier: frontend
      env: dev
  template:
    metadata:
      labels:
        app: coding-with-callie
        tier: frontend
        env: dev
    spec:
      containers:
      - name: frontend-container-dev
        image: 782831329154.dkr.ecr.us-east-1.amazonaws.com/coding-with-callie-frontend:latest
        env:
        - name: REACT_APP_API
          value: "/api"
        ports:
        - containerPort: 3000
