apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: coding-with-callie
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding-with-callie
      tier: frontend
  template:
    metadata:
      labels:
        app: coding-with-callie
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: 782831329154.dkr.ecr.us-east-1.amazonaws.com/coding-with-callie-frontend:v62
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: REACT_APP_API
          value: "/api"
        ports:
        - containerPort: 3000
