apiVersion: v1
kind: Service
metadata:
  name: frontend-service-dev
spec:
  selector:
    app: coding-with-callie
    tier: frontend
    env: dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000