apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrate-job
spec:
  template:
    spec:
      containers:
      - name: backend-container
        image: 782831329154.dkr.ecr.us-east-1.amazonaws.com/coding-with-callie-backend:v30
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_HOST
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_PASSWORD
        - name: DATABASE_NAME
          value: "postgres"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: ENVIRONMENT
          value: "production"
        command: ["npm", "run", "migration:run"]
      restartPolicy: Never
