apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: coding-with-callie
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding-with-callie
      tier: backend
  template:
    metadata:
      labels:
        app: coding-with-callie
        tier: backend
    spec:
      containers:
      - name: backend-container
        image: 782831329154.dkr.ecr.us-east-1.amazonaws.com/coding-with-callie-backend:v4
        readinessProbe:
          httpGet:
            path: /api/readyz
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_HOST
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: GMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gmail-secret
              key: GMAIL_PASSWORD
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: ACCESS_KEY
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: SECRET_ACCESS_KEY
        - name: DATABASE_NAME
          value: "postgres"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: ENVIRONMENT
          value: "production"
        ports:
        - containerPort: 3001
