name: Run NestJS Unit Tests
on:
  [push]
jobs:
  run-unit-tests:
    name: Run NestJS Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          cd api
          npm ci
      - name: build
        run: |
          cd api
          npm run build
      - name: Run unit tests
        run: |
          cd api
          npm run test