name: Run NestJS Unit Tests
on:
  push:
    branches: [ "cs-refactor-axios" ]
jobs:
  run-unit-tests:
    name: Run NestJS Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          cd api
          npm install
      - name: Run unit tests
        run: |
          cd api
          npm run test